version: '3' 
services: 
  dashboard_back:
    build: ./server/
    image: "node_back"
    container_name: "dashboard_back"
    environment:
      SECRET_TOKEN: YXJtYW5kb2JvbmQ=
    ports: 
      - "3000:3000"
    networks: 
      - back-end
    restart: always 
  dashboard_db:
    image: mongo
    container_name: "dashboard_db"
    volumes:
      - ./data-volume:/data/db/
    ports:
      - "27017:27017"
    networks:
      - back-end
  dashboard_front:
    build: ./client/
    image: "react_front"
    container_name: "dashboard_front"
    ports: 
      - "8080:8080"
    networks: 
      - back-end
    restart: always 

networks:
  back-end:
    driver: bridge